periodics:

- interval: 8h
  name: e2e-kops-aws-distro-imagedebian9
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-distro-debian-9.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-image=379101102735/debian-stretch-hvm-x86_64-gp2-2020-10-31-2842
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-distros
    testgrid-tab-name: kops-aws-distro-debian-9

- interval: 8h
  name: e2e-kops-aws-distro-imagedebian10
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-distro-debian-10.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-image=136693071363/debian-10-amd64-20201207-477
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-distros
    testgrid-tab-name: kops-aws-distro-debian-10

- interval: 8h
  name: e2e-kops-aws-distro-imageubuntu1804
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-distro-ubuntu-1804.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ubuntu
      - --env=KUBE_SSH_USER=ubuntu
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-image=099720109477/ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20201201
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-distros
    testgrid-tab-name: kops-aws-distro-ubuntu-18.04

- interval: 8h
  name: e2e-kops-aws-distro-imageubuntu2004
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-distro-ubuntu-2004.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ubuntu
      - --env=KUBE_SSH_USER=ubuntu
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-image=099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201201
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-distros
    testgrid-tab-name: kops-aws-distro-ubuntu-20.04

- interval: 8h
  name: e2e-kops-aws-distro-imagecentos7
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-distro-centos-7.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=centos
      - --env=KUBE_SSH_USER=centos
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-image=125523088429/CentOS 7.9.2009 x86_64
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-distros
    testgrid-tab-name: kops-aws-distro-centos-7

- interval: 8h
  name: e2e-kops-aws-distro-imagecentos8
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-distro-centos-8.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=centos
      - --env=KUBE_SSH_USER=centos
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-image=125523088429/CentOS 8.3.2011 x86_64
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-distros
    testgrid-tab-name: kops-aws-distro-centos-8

- interval: 8h
  name: e2e-kops-aws-distro-imageamazonlinux2
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-distro-amazonlinux-2.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ec2-user
      - --env=KUBE_SSH_USER=ec2-user
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-image=137112412989/amzn2-ami-hvm-2.0.20201126.0-x86_64-gp2
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-distros
    testgrid-tab-name: kops-aws-distro-amazonlinux-2

- interval: 8h
  name: e2e-kops-aws-distro-imagerhel7
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-distro-rhel-7.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ec2-user
      - --env=KUBE_SSH_USER=ec2-user
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-image=309956199498/RHEL-7.9_HVM_GA-20200917-x86_64-0-Hourly2-GP2
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-distros
    testgrid-tab-name: kops-aws-distro-rhel-7

- interval: 8h
  name: e2e-kops-aws-distro-imagerhel8
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-distro-rhel-8.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ec2-user
      - --env=KUBE_SSH_USER=ec2-user
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-image=309956199498/RHEL-8.3.0_HVM-20201031-x86_64-0-Hourly2-GP2
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-distros
    testgrid-tab-name: kops-aws-distro-rhel-8

- interval: 8h
  name: e2e-kops-aws-distro-imageflatcar
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-distro-flatcar.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=core
      - --env=KUBE_SSH_USER=core
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-image=075585003325/Flatcar-stable-2605.10.0-hvm
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-distros
    testgrid-tab-name: kops-aws-distro-flatcar
