presubmits:
  kubernetes-sigs/image-builder:
  - name: pull-azure-vhds
    labels:
      preset-azure-cred: "true"
    decorate: true
    run_if_changed: 'images/capi/.*'
    decoration_config:
      timeout: 1h
    max_concurrency: 5
    path_alias: sigs.k8s.io/image-builder
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
        args:
          - runner.sh
          - "./images/capi/packer/azure/scripts/ci-azure-e2e.sh"
        resources:
          requests:
            cpu: 1000m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-image-builder
      testgrid-tab-name: pr-azure-vhds
  - name: pull-azure-sigs
    labels:
      preset-azure-cred: "true"
    decorate: true
    always_run: false
    optional: true
    decoration_config:
      timeout: 1h
    max_concurrency: 5
    path_alias: sigs.k8s.io/image-builder
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
        args:
          - runner.sh
          - "./images/capi/packer/azure/scripts/ci-azure-e2e.sh"
        env:
          - name: AZURE_BUILD_FORMAT
            value: "sig"
        resources:
          requests:
            cpu: 1000m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-image-builder
      testgrid-tab-name: pr-azure-sigs
