presubmits:
  kubernetes-sigs/service-apis:
  - name: pull-service-apis-verify
    annotations:
      testgrid-dashboards: sig-network-service-apis
      testgrid-tab-name: verify
    labels:
      preset-kind-volume-mounts: "true"
      preset-dind-enabled: "true"
    decorate: true
    path_alias: sigs.k8s.io/service-apis
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
        command:
          # generic runner script, handles DIND, bazelrc for caching, etc.
          - runner.sh
        args:
          - make
          - verify
        # docker-in-docker needs privileged mode.
        securityContext:
          privileged: true
