presubmits:
  kubernetes-sigs/node-feature-discovery-operator:
  - name: pull-node-feature-discovery-operator-verify
    always_run: true
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: operator-verify
      description: "Verify source code of node-feature-discovery-operator: check formatting, lint etc."
    spec:
      containers:
      - image: golang:1.14
        command:
        - scripts/test-infra/verify.sh
  - name: pull-node-feature-discovery-operator-build-image
    always_run: true
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: operator-build-image
      description: "Build container image of node-feature-discovery-operator"
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
        securityContext:
          privileged: true
        command:
        - runner.sh
        args:
        - scripts/test-infra/build-image.sh
