presubmits:
  kubernetes/test-infra:
  - name: pull-test-infra-bazel
    branches:
    - master
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/launcher.gcr.io/google/bazel:v20201028-8000225-test-infra
        command:
        - hack/bazel.sh
        args:
        - test
        - --config=ci
        - --nobuild_tests_only
        - //...
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: bazel

  - name: pull-test-infra-gubernator
    branches:
    - master
    run_if_changed: 'gubernator|config/prow/config.yaml|config/jobs/.+\.yaml'
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gubernator:v20200824-5d057db
        command:
        - ./gubernator/test-gubernator.sh
        env:
        - name: WORKSPACE
          value: "/workspace"
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: gubernator

  - name: pull-test-infra-verify-file-perms
    branches:
    - master
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-experimental
        command:
        - ./hack/verify-file-perms.sh
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: verify-file-perms

  - name: pull-test-infra-yamllint
    always_run: true
    decorate: true
    spec:
      containers:
      - image: quay.io/kubermatic/yamllint:0.1
        command:
        - yamllint
        - -c
        - config/jobs/.yamllint.conf
        - config/jobs
        - config/prow/cluster
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: verify-yaml

  # Please keep this in sync with the `ci-test-infra-prow-checkconfig` job
  - name: pull-test-infra-prow-checkconfig
    decorate: true
    run_if_changed: '^(config/prow/(config|plugins).yaml$|config/jobs/.*.yaml$)'
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:v20201223-74663b53c1
        command:
        - /checkconfig
        args:
        - --config-path=config/prow/config.yaml
        - --job-config-path=config/jobs
        - --plugin-config=config/prow/plugins.yaml
        - --strict
        - --warnings=mismatched-tide-lenient
        - --warnings=tide-strict-branch
        - --warnings=needs-ok-to-test
        - --warnings=validate-owners
        - --warnings=missing-trigger
        - --warnings=validate-urls
        - --warnings=unknown-fields
        - --warnings=duplicate-job-refs
    annotations:
      testgrid-dashboards: presubmits-test-infra
  - name: pull-test-infra-integration
    branches:
    - master
    always_run: false
    decorate: true
    skip_report: true
    optional: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
        command:
        - runner.sh
        args:
        - prow/test/integration/test.sh
        - --config=ci
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: integration
